# Logger Config
logger_config:
  version: 1
  formatters:
    simple:
      format: "%(asctime)s — %(name)s — %(levelname)s — %(funcName)s:%(lineno)d — %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  root:
    level: DEBUG
    handlers: [console]

# Microsoft Azure Config
azure_container_name: covid19temp
azure_storage_account_name: azureopendatastorage
azure_storage_sas_token: sv=2019-02-02&ss=bfqt&srt=sco&sp=rlcup&se=2025-04-14T00:21:16Z&st=2020-04-13T16:21:16Z&spr=https&sig=JgwLYbdGruHxRYTpr5dxfJqobKbhGap8WUtKFadcivQ%3D

# Dataset Related Config
resources_dir: resources
dataset_dir: dataset
microsoft_cord_19_dataset_filepath: microsoft
microsoft_cord_19_dataset_filename: metadata.csv

# Microsoft CORD-19 dataset key
cord_uid_key: cord_uid
title_key: title
abstract_key: abstract

# Model Related Config
pretrained_models_path: resources/pretrained_models
model_name: biobert-nli
embedding_size: 768

# Embeddings Related Config
embeddings_path: generated_embeddings
title_embeddings_filename: title_embeddings.pkl
abstract_embeddings_filename: abstract_embeddings.pkl
sentence_embeddings_filename: sentence_embeddings.pkl

# SpaCy transformer_models
spacy_model_name: en_core_web_sm

# Vidhya UI resources
templates_dir: templates
static_dir: static